name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Since MultivariatePolynomials doesn't have binary dependencies,
        # only test on a subset of possible platforms.
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
          - version: '1.10'
            os: ubuntu-latest
            arch: x64
          - version: '1'
            os: ubuntu-latest
            arch: x86
          - version: 'pre'
            os: ubuntu-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: actions/checkout@v4
        with:
          repository: AayushSabharwal/MultivariatePolynomials.jl
          ref: as/poly-merge-nonconcrete
          path: upstream-MP
      - uses: actions/checkout@v4
        with:
          repository: AayushSabharwal/MutableArithmetics.jl
          ref: as+bl/simplify_promote_type_fallback
          path: upstream-MA
      - name: Use branch
        shell: julia --color=yes --project=@. {0}
        run: |
          using Pkg
          Pkg.develop([PackageSpec(; path = "upstream-MP"), PackageSpec(; path = "upstream-MA")])
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: yes
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
